# Generated by Django 4.1 on 2022-08-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='position',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
